// srcVue/App.vue
<script setup lang="ts">
import ParentComponent from "./ParentComponent.vue";
import { wrapper } from "../src/wrapper";
import { Parent } from "../src/types";
import { shallowRef, readonly } from "vue";

let value = shallowRef(wrapper);
const onAdd = (parent: Parent) => {
  value.value = { parent };
};
</script>

<template>
  <div className="App">
    <header class="App-header">
      <img alt="Vue logo" src="./assets/logo.png" class="App-logo" />
    </header>
    <ParentComponent :parent="readonly(value.parent)" @add="onAdd" />
    <pre style="background: lightgray; padding: 1rem">{{ value }}</pre>
  </div>
</template>

// srcReact/App.tsx
import logo from "./logo.svg";
import "./App.css";
import ParentComponent from "./ParentComponent";
import { wrapper } from "../src/wrapper";

const value = wrapper;

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo App-logo-react" alt="logo" />
      </header>
      <ParentComponent parent={value.parent} />
      <pre style={{ background: "lightgrey", padding: "1rem" }}>
        {JSON.stringify(value, null, 2)}
      </pre>
    </div>
  );
}

export default App;
