// srcVue/ChildComponent.vue
<script setup lang="ts">
import { defineProps, defineEmits } from "vue";
import { Child } from "../src/types";
import { updateValueOnChild } from "../src/helper";

const emit = defineEmits<{ (event: "input", child: Child): void }>();
const props = defineProps<{ child: Child }>();
const onInput = (event: Event) =>
  emit(
    "input",
    updateValueOnChild((event.currentTarget as HTMLInputElement).value)(
      props.child
    )
  );
</script>

<template>
  <div class="child">
    <input type="text" :value="props.child.value" @input="onInput" />
  </div>
</template>

// srcReact/ChildComponent.tsx
import React from "react";
import { Child } from "../src/types";
import { updateValueOnChild } from "../src/helper";

const ChildComponent = (props: {
  child: Child;
  setChild: (child: Child) => void;
}) => {
  const onInput = (event: React.FormEvent<HTMLInputElement>) =>
    props.setChild(updateValueOnChild(event.currentTarget.value)(props.child));
  return (
    <div className="child">
      <input defaultValue={props.child.value} type="text" onInput={onInput} />
    </div>
  );
};
export default ChildComponent;
