// srcVue/App.vue
<script setup lang="ts">
import ParentComponent from "./ParentComponent.vue";
import { wrapper } from "../src/wrapper";

const value = wrapper;
</script>

<template>
  <div className="App">
    <header class="App-header">
      <img alt="Vue logo" src="./assets/logo.png" class="App-logo" />
    </header>
    {{ value }}
    <ParentComponent :parent="value.parent" />
  </div>
</template>

// react/src/App.tsx
import logo from './logo.svg'
import './App.css'

const message = 'Hello World!';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <h1>{message}</h1>
      </header>
    </div>
  )
}

export default App
